language: python
python:

  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build

before_install:

# command to install dependencies
install:

script:
    - python3 tests/test.py

after_success:
    coveralls